<p class="1" style="text-align: center;" align="center"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">ПОЛЬЗОВАТЕЛЬСКОЕ СОГЛАШЕНИЕ</span></p>
<p class="1"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">&nbsp;</span></p>
<p class="1" style="text-align: justify; text-indent: 36.0pt;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">ТОО &laquo;ENRISE&raquo;</span> <span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">(далее - Поставщик), в лице Исполнительного директора Ералиевой Г., действующего на основании Доверенности №1 от 01.04.2019г, БИН 190340020765, юридический адрес (фактический адрес): Республика Казахстан, город Алматы, Медеуский район, улица Елебекова, дом 48, адрес электронной почты: info@en-rise.com, предлагает услуги по предоставлению доступа к информационному ресурсу, на определенных в настоящем Пользовательском соглашении условиях:</span></p>
<p class="1"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">&nbsp;</span></p>
<p class="1" style="text-align: center;" align="center"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">1. ПОНЯТИЯ И ТЕРМИНЫ, ИСПОЛЬЗУЕМЫЕ В НАСТОЯЩЕМ СОГЛАШЕНИИ</span></p>
<p class="1" style="text-align: justify;"><strong><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Интернет-сервис</span></strong><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;"> (далее Сайт или Интернет-сервис) - электронный информационный ресурс </span><a href="http://www.en-rise.com/"><span style="color: blue; background: white;">http://www.en-rise.com/</span></a><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">, технология его ведения и (или) использования, функционирующие в интернете, а также организационная структура, обеспечивающая информационное взаимодействие.</span></p>
<p class="1" style="text-align: justify;"><strong><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Пользователь</span></strong><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;"> - физическое и/или юридическое лицо, имеющий доступ к Сайту, посредством сети интернет и использующее Сайт и его сервисы.</span></p>
<p class="1" style="text-align: justify;"><strong><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Контент</span></strong><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;"> (содержание сайта) - информационное и техническое содержание сайта, охраняемые результаты интеллектуальной деятельности, включая весь контент, в т.ч. информация о Пользователе, его название, контактные данные, конфиденциальная информация, аннотации, иллюстрации, обложки, графические, текстовые производные, составные и иные произведения, пользовательские интерфейсы, визуальные интерфейсы, базы данных, а также дизайн, структура, выбор, координация, внешний вид, общий стиль и расположение данного содержания, входящего в состав Сайта и другие объекты интеллектуальной собственности все вместе и/или по отдельности, содержащиеся на Сайте.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">&nbsp;</span></p>
<p class="1" style="text-align: center;" align="center"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">2. ПРЕДМЕТ ПОЛЬЗОВАТЕЛЬСКОГО СОГЛАШЕНИЯ</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">2.1. Предметом настоящего пользовательского соглашения являются услуги по предоставлению Пользователю доступа к контенту, информации размещенным на Сайте и его сервисам, а также размещения информации о предоставляемых услугах, товарах и работах осуществляемых Пользователем.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">2.2. Интернет-сервис предоставляет Пользователю право использовать доступ к Сайту и его сервисам, для получения дохода (прямой или косвенной коммерческой выгоды) от такого использования, в том числе для собственного потребления, внутреннего использования.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">2.3. Пользователь дает свое согласие на хранение, использование, обработку и передачу создаваемого и размещаемого им контента на Сайте.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">&nbsp;</span></p>
<p class="1" style="text-align: center;" align="center"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.ПОРЯДОК И СПОСОБЫ ОПЛАТЫ УСЛУГ ИНТЕРНЕТ-СЕРВИСА</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.1. Оплата услуг Интернет-сервиса осуществляется Пользователем на условиях: безналичного перевода денег на расчетный счет Поставщика. </span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.2. Оплата услуг Интернет-сервиса осуществляется любым из способов, предложенных Сайтом. Некоторые способы оплаты Услуг могут предусматривать обязательство Пользователя по оплате комиссии или платы за услуги лиц, осуществляющих прием и перечисление платежей, банка и т. п.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">&nbsp;</span></p>
<p class="1" style="text-align: center;" align="center"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">4. ПОРЯДОК ЗАКЛЮЧЕНИЯ, ИЗМЕНЕНИЯ, РАСТОРЖЕНИЯ ПОЛЬЗОВАТЕЛЬСКОГО СОГЛАШЕНИЯ</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">4.1. Настоящее соглашение является публичной офертой. Получая доступ к Сайту и личному кабинету, пользователь считается совершившим акцепт, т.е. присоединившимся к настоящему соглашению. При совершении Пользователем акцепта считается, что пользовательское соглашение заключено, не требует двустороннего подписания и действительно в электронном виде.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">4.2. Пользователь обязан ознакомиться с Пользовательским соглашением до момента выполнения действий по совершению акцепта. Если Пользователь найдет условия Пользовательского соглашения неприемлемыми для себя - он не должен совершать действий по совершению акцепта.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">4.3. Интернет-сервис оставляет за собой право в любое время изменять, добавлять или удалять пункты настоящего Соглашения без уведомления Пользователя. Пользователь принимает на себя обязательство регулярно ознакамливаться с его условиями на предмет его изменения и (или) дополнения. Пользователь несет персональную ответственность за проверку настоящего Соглашения на наличие изменений в нём. Продолжение использования Сайта Пользователем означает принятие изменений и дополнений, внесенных в настоящее Соглашение.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">4.4. Интернет-сервис вправе передать права и обязанности по Пользовательскому соглашению другому лицу. Пользователь не вправе, без согласия Исполнителя, передавать права и обязанности по Пользовательскому соглашению другому лицу.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">4.5. Расторжение Пользовательского соглашения возможно по соглашению Сторон, а также в случае одностороннего отказа от исполнения Пользовательского соглашения (отказа от Пользовательского соглашения) по основаниям, предусмотренным Пользовательским соглашением и законодательством РК.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">4.6. Интернет-сервис вправе приостановить исполнение своих обязательств по Пользовательскому соглашению (отказаться от Пользовательского соглашения) либо отказаться от исполнения Пользовательского соглашения: </span></p>
<p class="1" style="text-align: justify; text-indent: 36.0pt;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">если Пользователь совершает действия, которые Интернет-сервис, исключительно по своему усмотрению квалифицирует как невыполнение и (или) ненадлежащее выполнение Пользователем обязательств, регламентированных Пользовательским соглашением, в том числе нарушение прав Интернет-сервиса и иных правообладателей на Объекты Сайта;</span></p>
<p class="1" style="text-align: justify; text-indent: 36.0pt;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">в случае отсутствия или недостаточности средств, необходимых для оплаты услуг Интернет-сервиса;</span></p>
<p class="1" style="text-align: justify; text-indent: 36.0pt;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">если действия Пользователя приводят к сбоям в работе Интернет-сервиса;</span></p>
<p class="1" style="text-align: justify; text-indent: 36.0pt;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">в иных случаях, которые Интернет-сервис, исключительно по своему усмотрению квалифицирует, что действия Пользователя влекут и (или) могут повлечь невыполнение и (или) ненадлежащее выполнение Пользователем обязательств, регламентированных Пользовательским соглашением, возможные (потенциальные) убытки и (или) риски и (или) угрозу их причинения и (или) возникновения для Интернет-сервиса.</span></p>
<p class="1"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">&nbsp;</span></p>
<p class="1" style="text-align: center;" align="center"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">6. СОГЛАСИЕ НА СБОР, ОБРАБОТКУ ПЕРСОНАЛЬНЫХ ДАННЫХ</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">6.1. В соответствии с законодательством, регламентирующим отношения, связанные со сбором, обработкой Персональных данных при совершении Пользователем Акцепта, в порядке определенном Пользовательским соглашением, Пользователь дает безусловное согласие Интернет-сервису и Третьим лицам на Сбор, Обработку, трансграничную передачу (при необходимости) Персональных данных Пользователя, не противоречащими законодательству способами.</span></p>
<p class="1"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">&nbsp;</span></p>
<p class="1" style="text-align: center;" align="center"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">8. ОТВЕТСТВЕННОСТЬ СТОРОН</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">8.1. Содержание контента (статей, ответов на вопросы, вебинаров, рекомендаций, процедур и т.д.) носят рекомендательный характер, выражают экспертное мнение специалиста и не являются обязательными для исполнения.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">8.2. За невыполнение и (или) ненадлежащее выполнение обязательств по Пользовательскому соглашению Стороны несут ответственность в соответствии с Пользовательским соглашением и действующим законодательством Республики Казахстан.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">8.3. Интернет-сервис не несет ответственности за причинение убытков, включая реальный, косвенный, случайный, неумышленный ущерб, упущенную выгоду, вред чести, достоинству или деловой репутации, потерю данных или за причинение любых других убытков Пользователю и третьим лицам, в т.ч. которые возникли при использовании или невозможности использования Сайта, или понесенных в результате ошибок, перерывов, дефектов, задержек в работе, изменения функций Сайта, или передачи и (или) потери данных.</span></p>
<p class="1"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">&nbsp;</span></p>
<p class="1" style="text-align: center;" align="center"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">9. ОБСТОЯТЕЛЬСТВА НЕПРЕОДОЛИМОЙ СИЛЫ (ФОРС-МАЖОР)</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">9.1. Сторона освобождается от ответственности за частичное или полное неисполнение, или ненадлежащее исполнение обязательства, если это явилось следствием обстоятельств непреодолимой силы, возникших после заключения Пользовательского соглашения в результате обстоятельств чрезвычайного характера, которые Сторона не могла предвидеть или предотвратить.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">9.2. Под обстоятельствами непреодолимой силы понимаются: наводнение, пожар, землетрясение, стихийные явления, аварии/сбои на сетях связи, разрушения зданий, сооружений и любых установок, сетей, телекоммуникационного оборудования, эпидемия, война или военные действия, а также решения органов государственной власти или управления.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">9.3. В случаях наступления обстоятельств непреодолимой силы срок выполнения Стороной обязательств по Пользовательскому соглашению отодвигается соразмерно времени, в течение которого действуют эти обстоятельства и их последствия. Если наступившие обстоятельства непреодолимой силы и их последствия продолжают действовать более 3 (трех) месяцев, Стороны проводят дополнительные переговоры для определения приемлемых альтернативных способов исполнения Пользовательского соглашения, или обязательства Сторон прекращаются невозможностью исполнения (за исключением денежных обязательств) с момента возникновения обстоятельств непреодолимой силы.</span></p>
<p class="1"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">&nbsp;</span></p>
<p class="1" style="text-align: center;" align="center"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">10. РАЗРЕШЕНИЕ СПОРОВ</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">10.1. Досудебное урегулирование спора осуществляется путем переговоров и предъявления претензий и является обязательным.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">10.2. Получатель претензии в течение 10 рабочих дней со дня её получения, письменно уведомляет заявителя о результатах рассмотрения претензии.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">10.3. При невозможности разрешить спор в досудебном порядке, любая из сторон вправе обратиться за защитой своих прав в судебные органы. Все споры разрешаются в суде исключительно по месту нахождения Интернет-сервиса.</span></p>
<p class="1"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">&nbsp;</span></p>
<p class="1" style="text-align: center;" align="center"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">11. ЗАКЛЮЧИТЕЛЬНЫЕ ПОЛОЖЕНИЯ</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">11.1. Пользовательское соглашение, а также все правоотношения, возникающие в связи с исполнением Пользовательского соглашения, регулируются и подлежат толкованию в соответствии с законодательством Республики Казахстан.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">11.2. Пользовательское соглашение вступает в силу в момент регистрации Пользователя на Интернет-сервисе и действует до момента полного исполнения Сторонами принятых на себя обязательств.</span></p>