<p class="1" style="text-align: center;" align="center"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">ПУБЛИЧНЫЙ ДОГОВОР ПОСТАВКИ ПРОДУКЦИИ</span></p>
<table class="MsoNormalTable" style="border-collapse: collapse; border: none;" border="1" width="602" cellspacing="0" cellpadding="0">
    <tbody>
    <tr>
        <td style="width: 225.7pt; border: solid white 1.0pt; padding: 5.0pt 5.0pt 5.0pt 5.0pt;" valign="top" width="301">
            <p class="1"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">г. Алматы&nbsp;&nbsp;&nbsp; </span></p>
        </td>
        <td style="width: 225.7pt; border: solid white 1.0pt; border-left: none; padding: 5.0pt 5.0pt 5.0pt 5.0pt;" valign="top" width="301">
            <p class="1" style="text-align: right;" align="right"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">&nbsp; &laquo;27 &raquo; мая 2019 г.</span></p>
        </td>
    </tr>
    </tbody>
</table>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">&nbsp;</span></p>
<p class="1" style="text-align: justify; text-indent: 36.0pt;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Настоящий &laquo;Договор поставки&raquo; (далее &laquo;Договор&raquo;) определяет взаимоотношения между&nbsp; ТОО &laquo;ENRISE&raquo;, именуемое в дальнейшем &ldquo;Поставщик&rdquo;, в лице Исполнительного директора Ералиевой Г., действующего на основании доверенности №1 от 01.04.2019, с одной стороны, и &laquo;Дистрибьютором&raquo; (физическим или юридическим лицом), принявшим публичное предложение (оферту) о заключении Договора. </span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">&nbsp;</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Термины и определения используемые в настоящем Договоре:</span></p>
<p class="1" style="text-align: justify;"><strong><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Договор </span></strong><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">- нижеизложенные условия, для установления правоотношений между сторонами.</span></p>
<p class="1" style="text-align: justify;"><strong><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Поставщик или Компания</span></strong><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;"> - ТОО &laquo;ENRISE&raquo;, юридическое лицо, учрежденное в соответствии с законодательством Республики Казахстан.</span></p>
<p class="1" style="text-align: justify;"><strong><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Дистрибьютор</span></strong><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;"> - физическое или юридическое лицо, являющееся стороной в данном Договоре.</span></p>
<p class="1" style="text-align: justify;"><strong><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Потребители </span></strong><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">- третьи лица, потребляющие Продукцию Поставщика.</span></p>
<ul style="margin-top: 10.0pt; margin-bottom: 10.0pt;">
    <li class="1" style="margin: 10pt 0cm 10pt 48.4px; text-align: center; text-indent: 0.4px;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Предмет договора</span></li>
</ul>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">1.1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Поставщик поставляет, а Дистрибьютор обязуется принять и оплатить стоимость продукции ТОО &laquo;ENRISE&raquo; (далее - Товар), а также другой продукции, поставляемой Поставщиком (далее &ndash; Продукция) в порядке и сроках в соответствии с условиями настоящего Договора.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">1.2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Дистрибьютор имеет право оказывать Поставщику маркетинговые (информационные) услуги, направленные на продвижение Товара, в соответствии с условиями настоящего Договора.</span></p>
<ul style="margin-top: 10.0pt; margin-bottom: 10.0pt;">
    <li class="1" style="margin: 10pt 0cm 10pt 48.4px; text-align: center; text-indent: 0.4px;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Цена</span></li>
</ul>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">2.1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Поставка продукции производится по отпускным ценам, установленным Поставщиком согласно Спецификации, действующей в день размещения Дистрибьютором соответствующего заказа. Цены в Спецификации указываются в тенге с учетом НДС. Поставщик вправе изменять цены и ассортимент продукции с предупреждением об этом Дистрибьютора за 3 (три) календарных дня до предполагаемой даты изменения цены посредством публикации уведомления на интернет &ndash;ресурсе </span><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">www</span><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">.</span><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">en</span><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">-</span><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">rise</span><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">.</span><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">com</span><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">2.2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Поставщик вправе предоставить Дистрибьютору скидки за проданный объем продукции. Размер и порядок предоставления скидок оформляется путем заключения Дополнительного Соглашения к Договору. </span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">2.3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Цена продукции включает в себя стоимость доставки.</span></p>
<ul style="margin-top: 10.0pt; margin-bottom: 10.0pt;">
    <li class="1" style="margin: 10pt 0cm 10pt 48.4px; text-align: center; text-indent: 0.4px;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Обязанности Сторон</span></li>
</ul>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Дистрибьютор&nbsp; обязуется:</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.1.1.&nbsp;&nbsp; произвести оплату стоимости продукции в порядке, установленном настоящим Договором;</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.1.2.&nbsp;&nbsp; в случае поступления жалобы от потребителя на продукцию Поставщика (устную либо письменную), сообщить Поставщику об этой жалобе в 3-х (три) дневный срок с момента обращения с предоставлением подтверждающих материалов: копии жалобы, данных потребителя др. В случае нарушения Покупателем данных требований, Поставщик несёт ответственность, в размере реального ущерба, причиненного потребителю;</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.1.3.&nbsp;&nbsp; в случае изменения юридического статуса, наименования, местонахождения, банковских реквизитов, изменения собственника, реорганизации, ликвидации, банкротства, наложения ареста на денежные средства и/или иное имущества, приостановления расходных операций по любым банковским счетам уполномоченным органом по решению любых уполномоченных органов, иных решений или действий в соответствии с законодательством Республики Казахстан в течение двух рабочих дней со дня принятия решения (уполномоченного органа Дистрибьютора либо государственного органа) письменно уведомить об этом Поставщика;</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.1.4.&nbsp;&nbsp; до подписания договора предоставить Поставщику копии следующих документов:</span></p>
<p class="1" style="text-align: justify; text-indent: 36.0pt;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">для физических лиц: удостоверение личности</span></p>
<p class="1" style="text-align: justify; text-indent: 36.0pt;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">для юридических лиц любой формы собственности: свидетельство о государственной регистрации/справка о гос.регистрации юридического лица, свидетельство о постановке на учет по НДС (при наличии), устав, приказ (и протокол) о назначении руководителя исполнительного органа, в случае, если договор подписывается не руководителем исполнительного органа - доверенность;</span></p>
<p class="1" style="text-align: justify; text-indent: 36.0pt;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">для индивидуальных предпринимателей: свидетельство индивидуального предпринимателя, удостоверение личности, документ, подтверждающий место жительства (с указанием адреса проживания).</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Покупатель также обязуется предоставить копию документа, подтверждающего его местонахождение (договор аренды, свидетельство о праве на недвижимое имущество и др.);</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.1.5.&nbsp;&nbsp; Дистрибьютор обязуется в целях предотвращения возможности нанесения убытков Поставщику письменно извещать его в течение 5 (пять) рабочих дней о ликвидации Дистрибьютора и о принятии уполномоченными органами в отношении Дистрибьютора решений/действий ограничительного характера, таких как: принудительная реорганизация или ликвидация Поставщика; приостановление расходных операций по любым банковским счетам Поставщика уполномоченным органом; арест денег и/или иного имущества Поставщика по решению любых уполномоченных органов; иных решений или действий в соответствии с законодательством Республики Казахстан;</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.1.6.&nbsp;&nbsp; Дистрибьютор не имеет право давать какие-либо обещания от имени Поставщика или делать заявления от ее имени;</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.1.7.&nbsp;&nbsp; Дистрибьютор не должен дискредитировать, ущемлять права других дистрибьюторов, переподписывать существующих дистрибьюторов в другие дистрибьюторские сети;</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.1.8.&nbsp;&nbsp; В случае расторжения настоящего Договора по инициативе Дистрибьютора, Дистрибьютор обязуется написать заявление о расторжении соглашения и предоставить его Поставщику. Действие соглашения прекращается с момента регистрации Поставщиком заявления о расторжении Договора</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.1.9.&nbsp;&nbsp; Дистрибьютор несет полную ответственность за уплату налогов с дохода, полученного в результате исполнения условий настоящего Договора;</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.1.10. Дистрибьютор не должен своими действиями провоцировать возникновение любых претензий, судебных исков, денежных и иных требований, которые могут быть предъявлены Поставщику в связи с какими-либо действиями Дистрибьютора.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.1.11. Дистрибьютор обязан использовать только действующие официальные печатные материалы Поставщика при продвижении Продукции или при предоставлении информации о характеристиках Продукции;</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.1.12. Дистрибьютор обязан воздержаться от любых заявлений касательно Продукции, прямых или косвенных, которые противоречат информационным материалам Поставщика;</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.1.13. Дистрибьютор не может размещать какую-либо рекламу без специального письменного разрешения Поставщика, выданного на основании соответствующего заявления;</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.1.14. Дистрибьютор не может использовать в какой-либо форме товарные знаки Поставщика без предварительного письменного разрешения Поставщика, за исключением случаев использования Продукции и форм товарных знаков, выпущенных Поставщиком и полученных Дистрибьютором по условиям настоящего Договора;</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.1.15. Дистрибьютор не может продавать Продукцию каким-либо организациям розничной торговли и лично не предлагать Продукцию для продажи в каких-либо помещениях розничной торговли, а также розничных интернет-магазинах, официально не утвержденных Поставщиком, кроме случаев прямо указанных в настоящем Договоре.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.1.16. Дистрибьютор гарантирует Поставщику, что имеет все полномочия и права для заключения и исполнения настоящего Договора и что совершая такие действия, он не нарушает какой-либо иной договор или соглашение, которое может препятствовать возложенные на себя обязательства по исполнению условий настоящего Договора.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Поставщик обязуется:</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.2.1. поставлять продукцию в сроки и на условиях настоящего Договора;</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.2.2. Поставщик может отказаться от исполнения своих обязательств по Договору, в том числе расторгнуть настоящий договор в одностороннем порядке без уведомления Дистрибьютора, если Дистрибьютор существенно нарушает условия Договора. К существенным нарушениям Дистрибьютором настоящего Договора, в частности относятся:</span></p>
<p class="1" style="text-align: justify; text-indent: 36.0pt;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">а)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; неоднократного и необоснованного отказа от приема заявленного продукции (более 3-х раз);</span></p>
<p class="1" style="text-align: justify; text-indent: 36.0pt;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">b)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; систематическое наличие (3 и более раз) необоснованных претензий со стороны Дистрибьютора по качеству поставляемой и/или поставленной Поставщиком в порядке и на условиях настоящего Договора продукции;</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">3.2.3.&nbsp;&nbsp; ежемесячно проводить сверку расчетов по произведенным&nbsp; поставкам продукции и платежам, для чего Поставщик готовит Акт сверки и направляет его Дистрибьютору в срок не позднее 15 (пятнадцатого) числа&nbsp; месяца, следующего за месяцем, по которому производится сверка. В случае не подписания Дистрибьютором Акта сверки либо непоступления от Дистрибьютора возражений по Акту сверки в срок до 20 (двадцатого) числа месяца, следующего за месяцем, по которому производится сверка, Акт сверки считается принятым в редакции Поставщика.</span></p>
<ul style="margin-top: 10.0pt; margin-bottom: 10.0pt;">
    <li class="1" style="margin: 10pt 0cm 10pt 48.4px; text-align: center; text-indent: 0.4px;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Качество</span></li>
</ul>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">4.1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Поставщик гарантирует, что качество продукции соответствует действующим в Республике Казахстан стандартам (нормативно-технической документации). Качество продукции подтверждается сертификатами соответствия. </span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">4.2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Дистрибьютор до подписания актов или накладных о приёмке продукции обязан произвести проверку продукции и в случае обнаружения несоответствия продукции действующим стандартам потребовать от Поставщика её замены.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">4.3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Поставщик обязуется предоставлять Дистрибьютору&nbsp; сертификаты соответствия на те виды продукции, по которым обязательное оформление и предоставление сертификатов установлено законодательством Республики Казахстан. За 5 (пять) календарных дней до истечения срока действия сертификата, Дистрибьютор обязуется потребовать от Поставщика новый сертификат или продленный, который Поставщик предоставляет не позднее 3 (три) дней с момента требования. В случае, если Дистрибьютор не потребует сертификат в указанный в данном пункте срок, Поставщик снимает с себя всякую ответственность за использование Дистрибьютором сертификата с истекшим сроком годности.</span></p>
<ul style="margin-top: 10.0pt; margin-bottom: 10.0pt;">
    <li class="1" style="margin: 10pt 0cm 10pt 48.4px; text-align: center; text-indent: 0.4px;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Доставка</span></li>
</ul>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">5.1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Объемы поставляемых партий определяются в соответствии с заявкой Дистрибьютора. В заявке указывается номер заказа, номер Договора, наименование, код, количество продукции. Отказ от получения заказанной продукции не допускается. Дистрибьютор обязан принять заказанную им продукцию. </span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">5.2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Дистрибьютор&nbsp; вправе отказаться от приема продукции, поставленной сверх указанного количества, либо завезенного без заявки или поставка которого просрочена.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">5.3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Днем исполнения обязательства по поставке продукции считается дата подтверждения Дистрибьютором приема продукции в соответствующих документах.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">5.4.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Продажа Продукции включает в себя стоимость доставки товара по территории Республики Казахстан.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">5.5.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Право собственности на продукции переходит к Дистрибьютору с момента ее приемки согласно п.6.6 настоящего договора.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">5.6.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Принятая не подлежащая приемке продукция согласно п.6.4. настоящего Договора не подлежит возврату.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">5.7.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; При приостановке производства вследствие различных причин Поставщик&nbsp; имеет право в одностороннем порядке сократить или прекратить поставку продукции с уведомлением об этом Дистрибьютора.</span></p>
<ul style="margin-top: 10.0pt; margin-bottom: 10.0pt;">
    <li class="1" style="margin: 10pt 0cm 10pt 48.4px; text-align: center; text-indent: 0.4px;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Приемка и возврат продукции</span></li>
</ul>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">6.1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Сдача и приемка продукции по количеству, ассортименту, качеству, осуществляется на складе Дистрибьютора по транспортным и сопроводительным документам на продукцию.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">6.2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Приемке подлежит только доброкачественная продукция, отвечающая требованиям государственных стандартов.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">6.3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Продукция принимается Дистрибьютором: </span></p>
<p class="1" style="text-align: justify; text-indent: 36.0pt;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">по качеству &ndash; согласно сертификатам качества, сертификатам соответствия;</span></p>
<p class="1" style="text-align: justify; text-indent: 36.0pt;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">по количеству &ndash; согласно расходной накладной и счет фактуры;</span></p>
<p class="1" style="text-align: justify; text-indent: 36.0pt;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">по цене &ndash; согласно утвержденному сторонами Прайс-листу.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">6.4.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Не подлежит приемке продукция, подлежащая обязательной сертификации и не имеющие сертификата соответствия, с истекшим сроком годности и с видимыми дефектами упаковки.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">6.5.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Отсутствие транспортных и сопроводительных документов является основанием для отказа в приеме продукции.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">6.6.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; При приемке продукции Дистрибьютор обязан выдать уполномоченному представителю Поставщика штамп доверенности и подписать накладную, если продукция поставлена в установленные сроки и отвечает требованиям Дистрибьютора согласно условиям настоящего договора.</span></p>
<ul style="margin-top: 10.0pt; margin-bottom: 10.0pt;">
    <li class="1" style="margin: 10pt 0cm 10pt 48.4px; text-align: center; text-indent: 0.4px;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Хранение и реализация</span></li>
</ul>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">7.1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Дистрибьютор обязан соблюдать Санитарные Правила для предприятий продовольственной торговли, несёт ответственность за правильность хранения и за своевременную реализацию продукции в соответствии с датой конечного срока реализации, указанной на потребительской упаковке (или товарно-транспортной накладной), не имеет права продавать бракованную продукцию либо продукцию с истекшим сроком годности.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">7.2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; В случае обнаружения брака в процессе реализации продукции с не истекшим сроком годности Дистрибьютор обязан известить Поставщика и совместно с представителем последнего выявить причину брака. Если обнаруженный брак произошел по обстоятельствам, за которые отвечает&nbsp; Поставщик, то данная продукция подлежит возврату или обмену. Возврат или обмен качественной продукции, полученной, но не реализованной Дистрибьютором до истечения сроков хранения (употребления), не производится.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">7.3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Если Дистрибьютором&nbsp; не соблюдаются указанные выше условия хранения и реализации, Поставщик имеет право прекратить дальнейшую поставку продукции с соответствующим уведомлением Дистрибьютора.</span></p>
<ul style="margin-top: 10.0pt; margin-bottom: 10.0pt;">
    <li class="1" style="margin: 10pt 0cm 10pt 48.4px; text-align: center; text-indent: 0.4px;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Тара</span></li>
</ul>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">8.1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Поставка продукции осуществляется в таре Поставщика.</span></p>
<ul style="margin-top: 10.0pt; margin-bottom: 10.0pt;">
    <li class="1" style="margin: 10pt 0cm 10pt 48.4px; text-align: center; text-indent: 0.4px;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Стоимость продукции и порядок расчетов</span></li>
</ul>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">9.1.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Дистрибьютор оплачивает стоимость поставленной Поставщиком продукции&nbsp; 100% авансовым безналичным либо наличным платежом. </span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">9.2.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Расчеты по настоящему Договору осуществляются по согласованию сторон&nbsp; одним из следующих способов: путем внесения Дистрибьютором соответствующих сумм наличных денег в кассу Поставщика, с соблюдением требований законодательства; путем перечисления денежных средств на расчетный счет Поставщика.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">9.3.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Днем оплаты считается день поступления денежных средств в кассу либо на расчетный счет Поставщика.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">9.4.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; В случае задержки платежа Поставщик&nbsp; имеет право приостановить поставку продукции с извещением об этом Дистрибьютора.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">9.5.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; В случае нарушения Дистрибьютором сроков оплаты стоимости продукции, Поставщик вправе применить одну или несколько одновременно из следующих санкций:</span></p>
<p class="1" style="text-align: justify; text-indent: 36.0pt;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">приостановить прием заявок и поставку продукции Дистрибьютору, до момента полной оплаты поставленной продукции;</span></p>
<p class="1" style="text-align: justify; text-indent: 36.0pt;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">потребовать от Дистрибьютора уплаты штрафной неустойки в размере 0,1% от суммы просроченного к оплате продукции за каждый день просрочки, включая стоимость тары (включая день платежа). Неустойка применяется как метод обеспечения обязательства. </span></p>
<p class="1" style="text-align: justify; text-indent: 36.0pt;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">приостановить оплату бонусов и других вознаграждений до полной оплаты суммы долга.</span></p>
<ul style="margin-top: 10.0pt; margin-bottom: 10.0pt;">
    <li class="1" style="margin: 10pt 0cm 10pt 48.4px; text-align: center; text-indent: 0.4px;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Форс-мажор</span></li>
</ul>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">10.1.&nbsp;&nbsp;&nbsp; В случае возникновения обстоятельств непреодолимой силы, которые могут воспрепятствовать полному или частичному исполнению любой из сторон своих обязательств по настоящему Договору, а именно: пожар, наводнение, эпидемия,&nbsp; стихийные бедствия, землетрясение, гражданские волнения, военные действия любого характера, акты государственных органов и другие обстоятельства, находящиеся вне контроля сторон ни одна из сторон не будет нести ответственность за полное или частичное неисполнение таких обязательств.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">10.2.&nbsp;&nbsp;&nbsp; Сторона, для которой стало невозможным исполнение своих обязательств, немедленно извещает&nbsp; в письменной форме другую сторону о возникновении обстоятельств непреодолимой силы.&nbsp; Такое уведомление должно содержать сведения о характере этих обстоятельств, а также оценку их воздействия на возможность&nbsp; исполнения обязательств по настоящему Договору. Уведомление направляется по почте заказным письмом с уведомлением о вручении.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">10.3.&nbsp;&nbsp;&nbsp; Не&nbsp; извещение другой стороны&nbsp; о Форс &ndash; Мажорных&nbsp; обстоятельствах&nbsp; в течение&nbsp;&nbsp;&nbsp; 30 (тридцати)&nbsp; календарных дней&nbsp; с момента их наступления лишает Сторону,&nbsp; попавшую под действие таких обстоятельств, ссылаться на них в качестве основания неисполнения этой&nbsp; Стороной своих обязательств по настоящему Договору.</span></p>
<ul style="margin-top: 10.0pt; margin-bottom: 10.0pt;">
    <li class="1" style="margin: 10pt 0cm 10pt 48.4px; text-align: center; text-indent: 0.4px;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Срок действия договора</span></li>
</ul>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">11.1.&nbsp;&nbsp;&nbsp; Настоящий Договор вступает в силу с момента его подписания обеими Сторонами и действует до &laquo;31&raquo; декабря 2020 г. По истечении срока действия Договора, при отсутствии уведомлений от Сторон о досрочном расторжении либо не продлении Договора, действие Договора продлевается на 1 (один) календарный год. Пролонгация Договора осуществляется не более 1 (одного) раза. В случае необходимости продления срока действия Договора на более длительный срок, Стороны обязаны заключить новый договор. </span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">11.2.&nbsp;&nbsp;&nbsp; Договор сохраняет свое действие, в том числе при досрочном расторжении, до тех пор, пока Стороны полностью не выполнят свои финансовые обязательства. </span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">11.3.&nbsp;&nbsp;&nbsp; Стороны могут расторгнуть Договор в любое время путем заключения дополнительного соглашения о расторжении Договор.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">11.4.&nbsp;&nbsp;&nbsp; Поставщик вправе расторгнуть договор в одностороннем порядке, предупредив об этом Дистрибьютора за 7 (семь) календарных дней до предполагаемой даты расторжения.</span></p>
<ul style="margin-top: 10.0pt; margin-bottom: 10.0pt;">
    <li class="1" style="margin: 10pt 0cm 10pt 48.4px; text-align: center; text-indent: 0.4px;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Споры и разногласия</span></li>
</ul>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">12.1.&nbsp;&nbsp;&nbsp; В случае если стороны не договорятся мирным путём, все споры и разногласия разрешаются в специализированном межрайонном экономическом суде города Алматы.</span></p>
<ul style="margin-top: 10.0pt; margin-bottom: 10.0pt;">
    <li class="1" style="margin: 10pt 0cm 10pt 48.4px; text-align: center; text-indent: 0.4px;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Прочие условия</span></li>
</ul>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">13.1.&nbsp;&nbsp;&nbsp; Настоящий Договор может быть дополнен и/или изменен в одностороннем порядке. Все изменения и дополнения в Договор, опубликовываются на официальном интернет ресурсе Компании. Дистрибьютор принимает на себя обязательства следить за актуальностью условий по Договору.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">13.2.&nbsp;&nbsp;&nbsp; Взаимоотношения Сторон по настоящему Договору, а также все прочее, в том числе не урегулированное настоящим Договором, но вытекающее из него, являются предметом действующего законодательства Республики Казахстан.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">13.3.&nbsp;&nbsp;&nbsp; Каждая Сторона обязуется не разглашать конфиденциальную информацию третьим лицам в течение срока действия настоящего договора, а также в течение 5 (пять) лет после его прекращения без письменного согласия другой стороны. Под конфиденциальной информацией Стороны договорились понимать содержание настоящего Договора, Приложения и Дополнительные соглашения к нему, а также любые сведения устного и зафиксированного на материальных носителях, включая данные в электронной форме, переданные одной Стороной другой Стороне в связи с заключением и исполнением Договора.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">13.4.&nbsp;&nbsp;&nbsp; Признание каких-либо положений настоящего Договора недействительными не влияет на действительность настоящего Договора в целом.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">13.5.&nbsp;&nbsp;&nbsp; Все Приложения к настоящему Договору являются его неотъемлемой частью после их подписания уполномоченными лицами Сторон.</span></p>
<ul style="margin-top: 10.0pt; margin-bottom: 10.0pt;">
    <li class="1" style="margin: 10pt 0cm 10pt 48.4px; text-align: center; text-indent: 0.4px;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">Досрочное расторжение договора</span></li>
</ul>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">14.1. До истечения срока действия договора, Поставщик вправе в одностороннем порядке полностью отказаться от исполнения своих обязательств по Договору,&nbsp; путем направления соответствующего уведомления Дистрибьютору за 7 (семи) календарных дней, если Дистрибьютор существенно нарушает условия Договора. К существенным нарушениям Покупателем настоящего Договора, относятся:</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; отсутствие заказов и приобретения продукции на срок 6 (шесть) и более месяцев подряд;</span></p>
<p class="1" style="text-align: justify; text-indent: 36.0pt;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">неоднократного и необоснованного отказа от приема заявленного продукции (более 3-х раз);</span></p>
<p class="1" style="text-align: justify; text-indent: 36.0pt;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">систематическое наличие (3 и более раз) необоснованных претензий со стороны Дистрибьютора по качеству поставляемой и/или поставленной Поставщиком в порядке и на условиях настоящего Договора продукции.&nbsp; </span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">14.2. До истечения срока действия договора, Поставщик вправе направить Дистрибьютору уведомление о расторжении Договора за 7 (семь) календарных дней до даты расторжения, на что Дистрибьютор в течении 7 (семи) календарных дней обязуется направить ответ о принятии такого условия либо отказа от него.</span></p>
<p class="1" style="text-align: justify;"><span style="font-size: 12.0pt; line-height: 115%; font-family: 'Times New Roman', serif;">14.3. До истечения срока действия договора, Поставщик вправе расторгнуть договор в одностороннем порядке, предупредив об этом Дистрибьютора за 7 (семь) календарных дней до предполагаемой даты расторжения.</span></p>
<p class="1">&nbsp;</p>